Feature/ape anx3 si 373 update dependency
anexia-it/serilog-sinks-cloudlog pull request #2
Opened 2022-12-02 17:28 UTC by anx-aperuzzi

ANX3SI-373: Tests created, publish.yml created, test.yml created

2022-12-02 18:06 UTC, beachmachine requested changes

2022-12-02 18:06 UTC, beachmachine commented on CHANGELOG.md
> +## [1.0.0] - 2022-12-01
Set date to 2022-12-05, as we will release on Monday.

2022-12-02 18:06 UTC, beachmachine commented on CHANGELOG.md
> +- Obsolete constructor call removed
Split in `Added`, `Changed` and `Removed`. See: https://github.com/anexia/dotnet-cloudlog/blob/main/CHANGELOG.md

2022-12-02 18:06 UTC, beachmachine commented on README.md
> +===============
The `===` line should equal the length of the text above.

2022-12-02 18:06 UTC, beachmachine commented on README.md
>  Serilog Sink for Anexia CloudLog
Update description to:

`serilog-sinks-cloudlog` is a Serilog sink that delivers log events to Anexia CloudLog.

**Note:** Usually it is considered best-practice to write rotating log-files to the filesystem, and send those logs to CloudLog via `Filebeat`.

2022-12-02 18:06 UTC, beachmachine commented on Serilog.Sinks.CloudLog.Test/CloudLogSinkTest.cs
> +}
Make sure there is a newline at the end of the file.

2022-12-02 18:06 UTC, beachmachine commented on src/Serilog.Sinks.CloudLog/Serilog.Sinks.CloudLog.csproj
>      <PackageReleaseNotes>Now honoring Serilog Reliability standards and no longer throwing an exception when the logger can not be configured.</PackageReleaseNotes>
Remove `PackageReleaseNotes`.

2022-12-02 18:06 UTC, beachmachine commented on src/Serilog.Sinks.CloudLog/Serilog.Sinks.CloudLog.csproj
> +    <TargetFrameworks>net5.0;net6.0;net7.0</TargetFrameworks>
`TargetFrameworks` is defined twice.

2022-12-02 18:06 UTC, beachmachine commented on src/Serilog.Sinks.CloudLog/Sinks/BatchedCloudLogEventSink.cs
> +}
Make sure there is a newline at the end of the file.

2022-12-02 18:06 UTC, beachmachine commented on src/Serilog.Sinks.CloudLog/Sinks/CloudLogSink.cs
> +}
Make sure there is a newline at the end of the file.

2022-12-02 18:06 UTC, beachmachine commented on src/Serilog.Sinks.CloudLog/Sinks/Formatting/CloudLogJsonFormatter.cs
> +        private static void FormatEvent(LogEvent logEvent, TextWriter output, JsonValueFormatter valueFormatter)
We manually write the JSON structure to the `TextWriter` in this method. Is this really how we should do that?

2022-12-02 18:06 UTC, beachmachine commented on README.md
>  ### Getting started
Split to `# Install` and `# Getting started` (mind the heading size; see: https://github.com/anexia/dotnet-cloudlog/blob/main/README.md).

2022-12-02 18:06 UTC, beachmachine commented on README.md
>  ### Getting started
Change the description of `Getting started` to:

With a correctly set up .NET SDK, run in `PowerShell`:

2022-12-02 18:06 UTC, beachmachine commented on README.md
>  ### Getting started
The example does not show the `using` imports, and does show how to use the sink with the Kafka protocol (which we just removed). Update the example to look like here: https://github.com/anexia/dotnet-cloudlog/blob/main/README.md

2022-12-02 18:06 UTC, beachmachine commented on Serilog.Sinks.CloudLog.Test/CloudLogSinkTest.cs
> +            Assert.Equal(result, 100);
Seems like the `actual` and the `expected` result are in the wrong order. Please fix throughout the tests.

2022-12-02 18:06 UTC, beachmachine commented on src/Serilog.Sinks.CloudLog/Sinks/Formatting/CloudLogJsonFormatter.cs
>      {
Add `private` to `_valueFormatter`, to be more consistent.

2022-12-05 08:37 UTC, anx-aperuzzi commented on src/Serilog.Sinks.CloudLog/Sinks/Formatting/CloudLogJsonFormatter.cs
> +        private static void FormatEvent(LogEvent logEvent, TextWriter output, JsonValueFormatter valueFormatter)
We could create a more object-oriented and somewhat faster approach. I did not touch it, since you told me not to edit too much. :D

2022-12-05 12:52 UTC, beachmachine approved these changes

2022-12-05 12:52 UTC, merged